### ISSUE TITLE
请删除 4.7.3 中的部分内容

### ISSUE THREAD

**Issue by zrong** [sixu05202004/pythontutorial#8]
http://www.pythondoc.com/pythontutorial27/controlflow.html#tut-arbitraryargs

下面这段以及之下的 4.7.3 的段落内容，都应该删除。 Python2 并不支持这种写法，若使用会报语法错误：

> 通常，这些 可变 参数是参数列表中的最后一个， 因为它们将把所有的剩余输入参数传递给函数。任何出现在 *args 后的参数是关键字参数，这意味着，他们只能被用作关键字，而不是位置参数。

英文文档中是没有这段的，参见：https://docs.python.org/2.7/tutorial/controlflow.html#arbitrary-argument-lists

**Comment by sixu05202004** [comment]
fix,thanks.
